### ISSUE TITLE
data.phpの問題点

### ISSUE THREAD

**Issue by sakash1ta90** [mono-taro/today_book#1]
- 不要なelse
if内部でreturn してるのとelse以降に処理がないのでelseでくくる必要がなさそうです。
 https://github.com/mono-taro/today_book/blob/030c9032112d36e0d35f42a790176c655063380c/data.php#L262

- 代入演算子による比較
https://github.com/mono-taro/today_book/blob/030c9032112d36e0d35f42a790176c655063380c/data.php#L303
比較ではなく代入しているようです。
L306も同様です

**Comment by mono-taro** [comment]
@sakash1ta90 様
ご指摘ありがとうございます！
早速、修正をさせていただきました！
